### ISSUE TITLE
Docs links are broken

### ISSUE THREAD

**Issue by apperside** [gid-oss/dataui-nestjs-crud#10]
Hello,
all the documentation related links in the readme are broken:

https://github.com/dataui/crud/wiki#why
https://github.com/dataui/crud/wiki/Controllers#description
https://github.com/dataui/crud/wiki/Services#description
https://github.com/dataui/crud/wiki/Requests#description

**Comment by afilp** [comment]
+1

**Comment by zaro** [comment]
The documentation is now deployed at  https://github.com/gid-oss/dataui-nestjs-crud , links are updated accordingly.
