### ISSUE TITLE
BUG: Incorrect result on searching with combination "$and" + "$or" conditions

### ISSUE THREAD

**Issue by PavloNaumenko** [gid-oss/dataui-nestjs-crud#26]
Example of the search parameter (based on [seeds](https://github.com/gid-oss/dataui-nestjs-crud/blob/master/integration/crud-typeorm/seeds.ts))
```js
{ name: { $eq: 'Project1' }, companyId: { $or: { $notnull: true, $eq: 1 } } }
```
Expectation:
The result is one project with the name `Project1`

Result:
Received all projects, filter `name: { $eq: 'Project1' }` is ignoring

**Comment by zaro** [comment]
@PavloNaumenko  Fix merged and released as `5.3.2`
