### ISSUE TITLE
npm broken documentation links

### ISSUE THREAD

**Issue by danyalutsevich** [gid-oss/dataui-nestjs-crud#28]
<img width="573" alt="Screenshot 2024-02-12 at 20 04 41" src="https://github.com/gid-oss/dataui-nestjs-crud/assets/83612717/500caf57-0b75-4167-b17c-9c6dbd9c2f61">

https://www.npmjs.com/package/@dataui/crud

the links in the npm package description leads to 404 pages

**Comment by zaro** [comment]
Thank you for the report.

Should be fixed now , thanks to @ZaidMaslouhi .
