### ISSUE TITLE
Bug: GetMany with join + pagination throws duplicate column error

### ISSUE THREAD

**Issue by ZaidMaslouhi** [gid-oss/dataui-nestjs-crud#32]
## Bug Report

I'm encountering an error when using getMany with joins and pagination. The issue seems to be related to duplicate column names in the query results.

- **Context:** Using getMany method in NestJS CRUD library.
- **Problem:** Duplicate column names appear in the query results when using joins and pagination together.
- **Impact:** This might lead to unexpected behavior and errors in your application.

**Comment by zaro** [comment]
Merged and released as 5.3.3.
