### ISSUE TITLE
empty schema for the Entity

### ISSUE THREAD

**Issue by its-dibo** [gid-oss/dataui-nestjs-crud#35]
after setup `@crud()` with typescript as mentioned in the docs, I opened the swagger UI to try out the routes that are created by this package.
it works, but I noticed that the schema is always empty

![image](https://github.com/gid-oss/dataui-nestjs-crud/assets/57308531/717659b8-a4ba-467d-81d2-b68f9b7c6ba5)

**solution:**
solved by adding `@nestjs/swagger` to plugins

nest-cli.json
```
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "deleteOutDir": true,
    "plugins": [
      {
        "name": "@nestjs/swagger",
        "options": {
          "introspectComments": true,
          "classValidatorShim": true
        }
      }
    ]
  }
}
```

**Comment by outp1** [comment]
I'm struggling with the same issue and this solution doesn't work. Can you please provide me a minimal reproduction repo, so i can see how you actually solved it? It would be really appreciated, man.

**Comment by its-dibo** [comment]
> can see how you actually solved it?

I updated the description with the solution before I closed the ticket

**Comment by outp1** [comment]
> > can see how you actually solved it?
> 
> I updated the description with the solution before I closed the ticket

Yes, I've seen it, but it's not a complete solution, adding a plugin doesn't solve anything for me.

**Comment by its-dibo** [comment]
> adding a plugin doesn't solve anything for me.

please give me more details or minimal reproduction so I can help you

**Comment by outp1** [comment]
> > adding a plugin doesn't solve anything for me.
> 
> please give me more details or minimal reproduction so I can help you

Here:
https://github.com/outp1/minimal-repro-repo
I've created a minimal reproduction with the same problem.

**Comment by its-dibo** [comment]
ok, I'll investigate your code.
but for now I just notice that you don't use `TypeOrm.forRoot()` [here](https://github.com/outp1/minimal-repro-repo/blob/309ca946b5d12723ff292127b23425b2b2675641/src/app.module.ts#L11)

**Comment by outp1** [comment]
> ok, I'll investigate your code. but for now I just notice that you don't use `TypeOrm.forRoot()` [here](https://github.com/outp1/minimal-repro-repo/blob/309ca946b5d12723ff292127b23425b2b2675641/src/app.module.ts#L11)

Cause i use `TypeOrmModule.forRootAsync()`

**Comment by outp1** [comment]
Can we reopen it? @its-dibo
