### ISSUE TITLE
Minor typo in main.yml: Docker Compose command

### ISSUE THREAD

**Issue by ZaidMaslouhi** [gid-oss/dataui-nestjs-crud#42]
### Description
This issue reports a minor typo in the main.yml file. The command used to start Docker Compose services has an extra hyphen before docker compose.

### Current Code:
`run: docker-compose up -d`

### Correct Code:
`run: docker compose up -d`

The hyphen before docker compose is unnecessary and might lead to errors when executing the command. Removing this hyphen ensures the command runs smoothly.

### Impact:

This typo could potentially cause the docker-compose up -d command to fail, preventing the intended action of starting all Docker Compose services in detached mode.

### Proposed Fix:

Simply remove the hyphen before docker compose in the _main.yml_ file.

**Comment by zaro** [comment]
@ZaidMaslouhi PR with the fix merged.
