### ISSUE TITLE
Wrong repo on npm

### ISSUE THREAD

**Issue by Limonische** [gid-oss/dataui-nestjs-crud#7]
First of all, thanks a lot for this fork and for keeping the lib alive, been using it since the guy from original library disappeared. The issue is that npm links to the wrong repo and so finding this one is really hard. The only direct link is in the issues for original lib.

**Comment by ionuts1704** [comment]
I have the same problem as @Limonische

**Comment by zaro** [comment]
@ionuts1704 fixed in the last version.
